### ISSUE TITLE
Performance counter dependencies bring in libstd

### ISSUE THREAD

**Issue by teisenbe** [gz/rust-x86#1] opened 2015-10-31 18:30 UTC
It might make sense to feature gate the performance counter code to allow library users to develop without a libstd

**Comment by gz** [comment] 2015-10-31 21:36
AFAIK the performance counters should work at the moment without libstd. I currently can not test it here (but I can look into it tomorrow).

The performance counters use rust-phf which is set to compile without std support in the rust-x86 Cargo.toml:
```
[dependencies.phf]
git = "https://github.com/sfackler/rust-phf.git"
features = ["core"]
```
The build process for rust-x86 does depend on libstd however. Is that a problem for you?

Gerd

**Comment by gz** [comment] 2015-10-31 21:37
I also noticed that rust-phf 0.7.6 which includes the core feature gate was released in the meantime. I will update Cargo.toml to use the cargo version instead of the git sources.

**Comment by teisenbe** [comment] 2015-10-31 21:43
I was having an issue in which if I listed the git version of your crate, the eh_personality and panic_fmt langitems would be getting defined elsewhere.  I worked around locally by just removing all of the external dependencies from the x86 create for now.  I can try to dig deeper next time I get a chance.

**Comment by gz** [comment] 2015-11-03 10:08
Interesting, I will have a look with the latest nightly then. I've never run into this so far.

**Comment by emk** [comment] 2015-11-12 13:15
Yup, I'm also seeing extra copies of `eh_personality` and `panic_fmt` getting pulled in, which are blocking me from using your lovely library. I'm going to investigate later.

**Comment by emk** [comment] 2015-11-12 14:00
OK, I've made a PR which adds a test case reproducing this problem.

I have a very selfish motive here: I want to write a blog post explaining how to handle interrupts, and I want to tell people to use gz/x86 because code reuse is awesome and only people who love pain should try to roll these data structures by hand. :-)

**Comment by gz** [comment] 2015-11-12 14:09
Hi, Many thanks! Unfortunately this issue got buried for me this week. Let me have a look now!

**Closed** 2015-11-12 17:01 UTC

**Comment by gz** [comment] 2015-11-12 17:05
The issue seemed not to be phf after all but rather bitflags which I think was never really no_std free but my older nightly did not seem to be bothered by that... 

@emk: I can compile your no_std_build.rs now with the latest commit:
rustc -L ../rust-x86/target/debug -L ../rust-x86/target/debug/deps --extern libc=/usr/local/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-8cf6ce90.rlib no_std_build.rs

Thanks for reporting and providing a pull request! Sorry for me taking so long to look into the issue.
